apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:ip-192-168-18-119.us-west-2.compute.internal
      groups:
        - system:bootstrappers
        - system:nodes
